### ISSUE TITLE
could not find or load main class com.google.zxing.client.j2se.CommandLineRunner

### ISSUE THREAD

**Issue by matthiasg** [komola/node-zxing#3]
i cannot run the test.js due to not finding the class `com.google.zxing.client.j2se.CommandLineRunner`. This is with java `1.8.0_25` on `Windows 10TP x64`.

**Comment by matthiasg** [comment]
the error is the `:` between the jars in the cmd line call. as per `java -help` it should be a semicolon.

**Comment by thomaschaaf** [comment]
Fixed in master :)

**Comment by matthiasg** [comment]
great ! thanks... easy fix.. but nice to see you and others response so fast !
